version: v1
globals:
  runner:
    os_image: ubuntu:20.04  # Use a stable Ubuntu version
  environment:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64

pipelines:
  default:
    steps:
      - name: Install Dependencies
        script:
          - echo "Updating system and installing dependencies"
          - apt-get update && apt-get install -y golang-go python3 python3-pip
          - python3 -m pip install --upgrade pip
          - pip3 install telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI psutil motor

      - name: Build Go Binary
        script:
          - echo "Verifying Go installation"
          - go version
          - echo "Tidying Go modules"
          - go mod tidy
          - echo "Building Go binary"
          - go build -ldflags="-w -s" -o raja raja.go
          - echo "Binary built successfully as 'raja'"

      - name: Run Python Script
        script:
          - echo "Giving execution permissions to Python script"
          - chmod +x d.py
          - echo "Running Python script"
          - python3 d.py
          
