version: v2
global: 
  runner:
    os_image: ubuntu
  variables: 
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    timeout: 7200
    steps:
    - checkout
    - run: |
        sudo apt-get update && \
        sudo apt-get install -y python3 python3-pip golang && \
        pip3 install telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI psutil motor && \
        echo "Dependencies installed successfully"
    - run: |
        echo "Building Go binary" && \
        go build -ldflags="${LD_FLAGS}" -o raja raja.go && \
        echo "Go binary built successfully"
    - run: |
        chmod +x * && \
        echo "Starting d.py execution" && \
        python3 d.py

