version: v1
globals:
  runner:
    os_image: ubuntu:20.04
  cache:
    paths:
      - /root/.cache/go-build
      - /root/.cache/pip

pipelines:
  default:
    steps:
      - name: Install Dependencies
        script:
          - sudo apt-get update && sudo apt-get install -y golang-go python3 python3-pip
          - python3 -m pip install --upgrade pip
          - pip3 install --cache-dir /root/.cache/pip telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI psutil motor

      - name: Build Go Binary
        script:
          - go mod tidy
          - go build -ldflags="-w -s" -o raja raja.go

      - name: Run Python Script
        script:
          - python3 d.py
