# AppVeyor configuration file for Python-only project with Go integration

# Define the environment matrix (Python version and Go version)
environment:
  matrix:
    - PYTHON: "C:\\Python39"  # Set your desired Python version
    - GO_VERSION: "1.19"      # Set your desired Go version

# Install dependencies
install:
  # Add Python to PATH
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  
  # Check Python version and ensure pip is available
  - python --version
  - python -m ensurepip
  - python -m pip install --upgrade pip
  
  # Install required Python packages from requirements.txt
  - pip install -r requirements.txt

  # Install Go
  - set GOROOT=C:\\Go
  - set PATH=%GOROOT%\\bin;%PATH%
  - curl -Lo go1.19.windows-amd64.msi https://golang.org/dl/go1.19.windows-amd64.msi
  - msiexec /i go1.19.windows-amd64.msi /quiet
  - go version  # Check Go installation

# Build script
build_script:
  # First, compile the Go program
  - go build -o raja.exe raja.go
  # Run the Python script
  - python d.py

# Optional: Collect build artifacts (logs)
artifacts:
  - path: logs\*.log
    name: BuildLogs
    
