# AppVeyor configuration file for Python-only project with C++ compilation

# Define the environment matrix (Python version)
environment:
  matrix:
    - PYTHON: "C:\\Python39"  # Set your desired Python version

# Install dependencies
install:
  # Add Python to PATH
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  
  # Check Python version and ensure pip is available
  - python --version
  - python -m ensurepip
  - python -m pip install --upgrade pip
  
  # Install required Python packages from requirements.txt
  - pip install -r requirements.txt

  # Install C++ build tools (e.g., MinGW or Visual Studio C++ Build Tools)
  - choco install mingw --version 8.1.0  # Install MinGW for g++ on Windows
  
  # Alternatively, use Visual Studio Build Tools (if you prefer `cl` compiler)
  # - choco install visualstudio2019buildtools

# Build script
build_script:
  # Compile the C++ source file (assuming raja.cpp)
  - g++ -pthread -o raja raja.cpp  # Compile raja.cpp to raja.exe
  # Run the Python script
  - python d.py

# Optional: Collect build artifacts (logs)
artifacts:
  - path: logs\*.log
    name: BuildLogs
    
